invoo/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'
  get 'home', to: 'pages#home'
  get 'exceptions', to: 'pages#exceptions'
  get 'from-to', to: 'pages#from_to'
  get 'balancete', to: 'pages#balancete'
  get 'balanco-patrimonial', to: 'pages#balance_sheet'
  get 'default_login', to: 'companies#default_login'
  get 'teste', to: 'import_account#teste'

  resources :companies do
    member do
      post :company_session
    end
    resources :import_accounts do
      collection do
        post :import
        get :edit
        patch :update
      end
    end
    resources :balance_sheets, only: [:index] do
      collection do
        get :graphs
      end
    end
    resources :dre, only: [:index] do
      collection do
        get :graphs
      end
    end
    resources :from_to, only: [:index]
    resources :exceptions, only: [:index]
    resources :orders
  end
end

invoo/app/controllers/from_to_controller.rb
class FromToController < ApplicationController
  def index
    @import_accounts = ImportAccount.all.sort_by &:client_account_number
  end
end

invoo/app/views/from_to/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2><strong>Verificação do De-Para</strong></h2>
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <i> <%= link_to 'Cadastro', new_company_path %> </i>
          </li>
          <li class="breadcrumb-item">
            <i><%= link_to 'Importação', new_company_import_account_path(session[:current_company_id]) %></i>
          </li>
          <li class="breadcrumb-item">
            <i> <%= link_to 'De-Para', edit_company_import_accounts_path(session[:current_company_id]) %> </i>
          </li>
          <li class="breadcrumb-item active">
            <strong>Verificação do De-Para</strong>
          </li>
        </ol>
  </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox ">
        <div class="ibox-title">
            <h5>Tabela De-Para</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
                <!-- <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-wrench"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="#" class="dropdown-item">Config option 1</a>
                    </li>
                    <li><a href="#" class="dropdown-item">Config option 2</a>
                    </li>
                </ul> -->
                <a class="close-link">
                    <i class="fa fa-times"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content">
          <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover dataTables-example" >
              <thead>
                <tr>
                  <th class="text-center" colspan="2">Balancete</th>
                  <th class="text-center" colspan="3">De-Para</th>
                </tr>
                <tr>
                  <th class="text-center">Conta</th>
                  <th class="text-center">Descrição</th>
                  <th class="text-center">Grupo</th>
                  <th class="text-center">Sub-Grupo</th>
                  <th class="text-center">Conta Ref.</th>
                </tr>
              </thead>
              <tbody>

              <% @import_accounts.each do |row| %>
                <tr class="gradeX">
                  <td><%= row.client_account_number %></td>
                  <td><%= row.client_account_description %></td>
                  <td> <%= row.chart_of_account.group %></td>
                  <td> <%= row.chart_of_account.sub_group %></td>
                  <td> <%= row.chart_of_account.account %></td>
                </tr>

           <!--   <%# @group.each do |group| %>
                <%# @sub_group.each do |sub_group| %>
                  <tr class="gradeX">
                    <td><%#= group["group"] %></td>
                    <td><%#= sub_group["sub_group"] %></td>

                  </tr>

                <%# end %> -->

              <% end %>
             </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>