inspinia-template/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
# You can have the root of your site routed with "root"

  # devise_for :users
  # root to: 'pages#home'
  # root to: 'dashboards#dashboard_1'
  root to: 'landing#index'
  get "balancetes/import"

  # All routes
  get "dashboards/dashboard_1"
  get "dashboards/dashboard_2"
  get "dashboards/dashboard_3"
  get "dashboards/dashboard_4"
  get "dashboards/dashboard_4_1"
  get "dashboards/dashboard_5"

  get "layoutsoptions/index"
  get "layoutsoptions/off_canvas"

  get "graphs/flot"
  get "graphs/morris"
  get "graphs/rickshaw"
  get "graphs/chartjs"
  get "graphs/chartist"
  get "graphs/peity"
  get "graphs/sparkline"
  get "graphs/c3charts"

  get "mailbox/inbox"
  get "mailbox/email_view"
  get "mailbox/compose_email"
  get "mailbox/email_templates"
  get "mailbox/basic_action_email"
  get "mailbox/alert_email"
  get "mailbox/billing_email"

  get "metrics/index"

  get "widgets/index"

  get "forms/basic_forms"
  get "forms/advanced"
  get "forms/wizard"
  get "forms/file_upload"
  get "forms/text_editor"
  get "forms/autocomplete"
  get "forms/markdown"

  get "appviews/contacts"
  get "appviews/profile"
  get "appviews/profile_two"
  get "appviews/contacts_two"
  get "appviews/projects"
  get "appviews/project_detail"
  get "appviews/activity_stream"
  get "appviews/file_menager"
  get "appviews/vote_list"
  get "appviews/calendar"
  get "appviews/faq"
  get "appviews/timeline"
  get "appviews/pin_board"
  get "appviews/teams_board"
  get "appviews/social_feed"
  get "appviews/clients"
  get "appviews/outlook_view"
  get "appviews/blog"
  get "appviews/article"
  get "appviews/issue_tracker"

  get "pages/search_results"
  get "pages/lockscreen"
  get "pages/invoice"
  get "pages/invoice_print"
  get "pages/login"
  get "pages/login_2"
  get "pages/forgot_password"
  get "pages/register"
  get "pages/not_found_error"
  get "pages/internal_server_error"
  get "pages/empty_page"

  get "miscellaneous/notification"
  get "miscellaneous/nestablelist"
  get "miscellaneous/timeline_second_version"
  get "miscellaneous/forum_view"
  get "miscellaneous/forum_post_view"
  get "miscellaneous/google_maps"
  get "miscellaneous/datamaps"
  get "miscellaneous/social_buttons"
  get "miscellaneous/code_editor"
  get "miscellaneous/modal_window"
  get "miscellaneous/validation"
  get "miscellaneous/tree_view"
  get "miscellaneous/chat_view"
  get "miscellaneous/agile_board"
  get "miscellaneous/diff"
  get "miscellaneous/pdf_viewer"
  get "miscellaneous/sweet_alert"
  get "miscellaneous/idle_timer"
  get "miscellaneous/spinners"
  get "miscellaneous/spinners_usage"
  get "miscellaneous/live_favicon"
  get "miscellaneous/masonry"
  get "miscellaneous/tour"
  get "miscellaneous/loading_buttons"
  get "miscellaneous/clipboard"
  get "miscellaneous/text_spinners"
  get "miscellaneous/truncate"
  get "miscellaneous/password_meter"
  get "miscellaneous/i18support"

  get "uielements/typography"
  get "uielements/icons"
  get "uielements/draggable_panels"
  get "uielements/resizeable_panels"
  get "uielements/buttons"
  get "uielements/video"
  get "uielements/tables_panels"
  get "uielements/tabs"
  get "uielements/notifications_tooltips"
  get "uielements/helper_classes"
  get "uielements/badges_labels_progress"

  get "gridoptions/index"

  get "tables/static_tables"
  get "tables/data_tables"
  get "tables/foo_tables"
  get "tables/jqgrid"

  get "commerce/products_grid"
  get "commerce/products_list"
  get "commerce/product_edit"
  get "commerce/product_detail"
  get "commerce/orders"
  get "commerce/cart"
  get "commerce/payments"

  get "gallery/basic_gallery"
  get "gallery/slick_carusela"
  get "gallery/bootstrap_carusela"

  get "cssanimations/index"

  get "landing/index"

end

inspinia-template/app/views/pages/empty_page.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>This is main title</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="<%= url_for :controller => 'dashboards', :action => 'dashboard_1' %>">This is</a>
            </li>
            <li class="breadcrumb-item active">
                <strong>Breadcrumb</strong>
            </li>
        </ol>
    </div>
    <div class="col-sm-8">
        <div class="title-action">
            <a href="" class="btn btn-primary">This is action area</a>
        </div>
    </div>
</div>
<div class="wrapper wrapper-content">
<div class="middle-box text-center animated fadeInRightBig">
    <h3 class="font-bold">This is page content</h3>
    <div class="error-desc">
        You can create here any grid layout you want. And any variation layout you imagine:) Check out
        main dashboard and other site. It use many different layout.
        <br/><a href="<%= url_for :controller => 'dashboards', :action => 'dashboard_1' %>" class="btn btn-primary m-t">Dashboard</a>
    </div>
</div>
</div>

inspinia-template/app/views/pages/forgot_password.html.erb
<div class="passwordBox animated fadeInDown">
    <div class="row">

        <div class="col-md-12">
            <div class="ibox-content">

                <h2 class="font-bold">Esqueceu sua senha?</h2>

                <p>
                    Entre seu endereço de email para que possamos lhe enviar as instruções de redefinição de senha.
                </p>

                <div class="row">

                    <div class="col-lg-12">
                        <form class="m-t" role="form" action="<%= url_for :controller => 'dashboards', :action => 'dashboard_1' %>">
                            <div class="form-group">
                                <input type="email" class="form-control" placeholder="Endereço de Email" required="">
                            </div>

                            <button type="submit" class="btn btn-primary block full-width m-b">Redefinir minha senha</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

inspinia-template/app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
teste

inspinia-template/app/views/pages/index.html.erb
<%= @row %>

<div class="container">
  <h3>Import Balances</h3>
  <%= form_tag import_balancetes_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Upload Balances" %>
  <% end %>

  <div class="container">
    <table class="table table-striped">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Conta</th>
          <th scope="col">Reduzido</th>
          <th scope="col">Descrição</th>
          <th scope="col">Anterior</th>
          <th scope="col">Débitos</th>
          <th scope="col">Créditos</th>
          <th scope="col">Movimento</th>
          <th scope="col">Saldo Atual</th>
        </tr>
      </thead>
      <tbody>
        <% if @balancetes.empty? %>
         <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        <% else %>
          <% @balancetes.each do |row| %>
            <tr>
              <td scope="row"><%= row.cd_financial_account_company %></td>
              <td><%= row.cd_financial_account_company_reduction %></td>
              <td><%= row.financial_account_description %></td>
              <td><%= row.anterior %></td>
              <td><%= row.debt %></td>
              <td><%= row.credit %></td>
              <td><%= row.moviment %></td>
              <td><%= row.current_balance %></td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

inspinia-template/app/views/pages/internal_server_error.html.erb
<div class="middle-box text-center animated fadeInDown">
    <h1>500</h1>
    <h3 class="font-bold">Internal Server Error</h3>

    <div class="error-desc">
        The server encountered something unexpected that didn't allow it to complete the request. We apologize.<br/>
        You can go back to main page: <br/><a href="<%= url_for :controller => 'dashboards', :action => 'dashboard_1' %>" class="btn btn-primary m-t">Dashboard</a>
    </div>
</div>



inspinia-template/app/views/pages/invoice.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-8">
        <h2>Invoice</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="<%= url_for :controller => 'dashboards', :action => 'dashboard_1' %>">Home</a>
            </li>
            <li class="breadcrumb-item">
                Other Pages
            </li>
            <li class="breadcrumb-item active">
                <strong>Invoice</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-4">
        <div class="title-action">
            <a href="#" class="btn btn-white"><i class="fa fa-pencil"></i> Edit </a>
            <a href="#" class="btn btn-white"><i class="fa fa-check "></i> Save </a>
            <a href="<%= url_for :controller => 'pages', :action => 'invoice_print' %>" target="_blank" class="btn btn-primary"><i class="fa fa-print"></i> Print Invoice </a>
        </div>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
<div class="row">
    <div class="col-lg-12">

        <div class="ibox-content p-xl">
            <div class="row">
                <div class="col-sm-6">
                    <h5>From:</h5>
                    <address>
                        <strong>Inspinia, Inc.</strong><br/>
                        106 Jorg Avenu, 600/10<br/>
                        Chicago, VT 32456<br/>
                        <abbr title="Phone">P:</abbr> (123) 601-4590
                    </address>
                </div>

                <div class="col-sm-6 text-right">
                    <h4>Invoice No.</h4>
                    <h4 class="text-navy">INV-000567F7-00</h4>
                    <span>To:</span>
                    <address>
                        <strong>Corporate, Inc.</strong><br/>
                        112 Street Avenu, 1080<br/>
                        Miami, CT 445611<br/>
                        <abbr title="Phone">P:</abbr> (120) 9000-4321
                    </address>
                    <p>
                        <span><strong>Invoice Date:</strong> Marh 18, 2014</span><br/>
                        <span><strong>Due Date:</strong> March 24, 2014</span>
                    </p>
                </div>
            </div>

            <div class="table-responsive m-t">
                <table class="table invoice-table">
                    <thead>
                    <tr>
                        <th>Item List</th>
                        <th>Quantity</th>
                        <th>Unit Price</th>
                        <th>Tax</th>
                        <th>Total Price</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>
                            <div><strong>Admin Theme with psd project layouts</strong></div>
                            <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</small>
                        </td>
                        <td>1</td>
                        <td>$26.00</td>
                        <td>$5.98</td>
                        <td>$31,98</td>
                    </tr>
                    <tr>
                        <td>
                            <div><strong>Wodpress Them customization</strong></div>
                            <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                                Eiusmod tempor incididunt ut labore et dolore magna aliqua.
                            </small>
                        </td>
                        <td>2</td>
                        <td>$80.00</td>
                        <td>$36.80</td>
                        <td>$196.80</td>
                    </tr>
                    <tr>
                        <td>
                            <div><strong>Angular JS & Node JS Application</strong></div>
                            <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</small>
                        </td>
                        <td>3</td>
                        <td>$420.00</td>
                        <td>$193.20</td>
                        <td>$1033.20</td>
                    </tr>

                    </tbody>
                </table>
            </div>
            <!-- /table-responsive -->

            <table class="table invoice-total">
                <tbody>
                <tr>
                    <td><strong>Sub Total :</strong></td>
                    <td>$1026.00</td>
                </tr>
                <tr>
                    <td><strong>TAX :</strong></td>
                    <td>$235.98</td>
                </tr>
                <tr>
                    <td><strong>TOTAL :</strong></td>
                    <td>$1261.98</td>
                </tr>
                </tbody>
            </table>
            <div class="text-right">
                <button class="btn btn-primary"><i class="fa fa-dollar"></i> Make A Payment</button>
            </div>

            <div class="well m-t"><strong>Comments</strong>
                It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less
            </div>
        </div>
    </div>
</div>
</div>


inspinia-template/app/views/pages/invoice_print.html.erb
<div class="wrapper wrapper-content p-xl">
    <div class="ibox-content p-xl">
        <div class="row">
            <div class="col-sm-6">
                <h5>From:</h5>
                <address>
                    <strong>Inspinia, Inc.</strong><br/>
                    106 Jorg Avenu, 600/10<br/>
                    Chicago, VT 32456<br/>
                    <abbr title="Phone">P:</abbr> (123) 601-4590
                </address>
            </div>

            <div class="col-sm-6 text-right">
                <h4>Invoice No.</h4>
                <h4 class="text-navy">INV-000567F7-00</h4>
                <span>To:</span>
                <address>
                    <strong>Corporate, Inc.</strong><br/>
                    112 Street Avenu, 1080<br/>
                    Miami, CT 445611<br/>
                    <abbr title="Phone">P:</abbr> (120) 9000-4321
                </address>
                <p>
                    <span><strong>Invoice Date:</strong> Marh 18, 2014</span><br/>
                    <span><strong>Due Date:</strong> March 24, 2014</span>
                </p>
            </div>
        </div>

        <div class="table-responsive m-t">
            <table class="table invoice-table">
                <thead>
                <tr>
                    <th>Item List</th>
                    <th>Quantity</th>
                    <th>Unit Price</th>
                    <th>Tax</th>
                    <th>Total Price</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><div><strong>Admin Theme with psd project layouts</strong></div>
                        <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</small></td>
                    <td>1</td>
                    <td>$26.00</td>
                    <td>$5.98</td>
                    <td>$31,98</td>
                </tr>
                <tr>
                    <td><div><strong>Wodpress Them customization</strong></div>
                        <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                            Eiusmod tempor incididunt ut labore et dolore magna aliqua.
                        </small></td>
                    <td>2</td>
                    <td>$80.00</td>
                    <td>$36.80</td>
                    <td>$196.80</td>
                </tr>
                <tr>
                    <td><div><strong>Angular JS & Node JS Application</strong></div>
                        <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</small></td>
                    <td>3</td>
                    <td>$420.00</td>
                    <td>$193.20</td>
                    <td>$1033.20</td>
                </tr>

                </tbody>
            </table>
        </div><!-- /table-responsive -->

        <table class="table invoice-total">
            <tbody>
            <tr>
                <td><strong>Sub Total :</strong></td>
                <td>$1026.00</td>
            </tr>
            <tr>
                <td><strong>TAX :</strong></td>
                <td>$235.98</td>
            </tr>
            <tr>
                <td><strong>TOTAL :</strong></td>
                <td>$1261.98</td>
            </tr>
            </tbody>
        </table>
        <div class="well m-t"><strong>Comments</strong>
            It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less
        </div>
    </div>

</div>

inspinia-template/app/views/pages/lockscreen.html.erb
<div class="lock-word animated fadeInDown">
    <span class="first-word">LOCKED</span><span>SCREEN</span>
</div>
<div class="middle-box text-center lockscreen animated fadeInDown">
<div>
    <div class="m-b-md">
        <img alt="image" class="rounded-circle circle-border" src="https://s3.amazonaws.com/uifaces/faces/twitter/ok/128.jpg">
    </div>
    <h3>John Smith</h3>
    <p>Your are in lock screen. Main app was shut down and you need to enter your passwor to go back to app.</p>
    <form class="m-t" role="form" action="<%= url_for :controller => 'dashboards', :action => 'dashboard_1' %>">
        <div class="form-group">
            <input type="password" class="form-control" placeholder="******" required="">
        </div>
        <button type="submit" class="btn btn-primary block full-width">Unlock</button>
    </form>
</div>
</div>


inspinia-template/app/views/pages/login.html.erb
<div class="middle-box text-center loginscreen animated fadeInDown">
    <div>
        <div>

            <h1 class="logo-name">IN+</h1>

        </div>
        <h3>Welcome to IN+</h3>
        <p>Perfectly designed and precisely prepared admin theme with over 50 pages with extra new web app views.
            <!--Continually expanded and constantly improved Inspinia Admin Them (IN+)-->
        </p>
        <p>Login in. To see it in action.</p>
        <form class="m-t" role="form" action="<%= url_for :controller => 'dashboards', :action => 'dashboard_1' %>">
            <div class="form-group">
                <input type="email" class="form-control" placeholder="Username" required="">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" placeholder="Password" required="">
            </div>
            <button type="submit" class="btn btn-primary block full-width m-b">Login</button>

            <a href="#"><small>Forgot password?</small></a>
            <p class="text-muted text-center"><small>Do not have an account?</small></p>
            <a class="btn btn-sm btn-white btn-block" href="<%= url_for :controller => 'pages', :action => 'register' %>">Create an account</a>
        </form>
        <p class="m-t"> <small>Inspinia we app framework base on Bootstrap 3 &copy; 2014</small> </p>
    </div>
</div>

inspinia-template/app/views/pages/login_2.html.erb
<div class="loginColumns animated fadeInDown">
    <div class="row">

        <div class="col-md-6">
            <h2 class="font-bold">Bem Vindo - Vamos Entrar?</h2>

            <p>
                Perfectly designed and precisely prepared admin theme with over 50 pages with extra new web app views.
            </p>

            <p>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
            </p>

            <p>
                When an unknown printer took a galley of type and scrambled it to make a type specimen book.
            </p>

        </div>
        <div class="col-md-6">
            <div class="ibox-content">
                <form class="m-t" role="form" action="<%= url_for :controller => 'dashboards', :action => 'dashboard_1' %>">
                    <div class="form-group">
                        <input type="email" class="form-control" placeholder="E-mail" required="">
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" placeholder="Senha" required="">
                    </div>
                    <button type="submit" class="btn btn-primary block full-width m-b">Entrar</button>

                    <a href="forgot_password">
                        <small>Esqueceu sua senha?</small>
                    </a>

                    <p class="text-muted text-center">
                        <small>Não tem uma conta ainda?</small>
                    </p>
                    <a class="btn btn-sm btn-white btn-block" href="<%= url_for :controller => 'pages', :action => 'register' %>">Crie sua conta</a>
                </form>
            </div>
        </div>
    </div>

</div>

inspinia-template/app/views/pages/not_found_error.html.erb
<div class="middle-box text-center animated fadeInDown">
    <h1>404</h1>
    <h3 class="font-bold">Page Not Found</h3>

    <div class="error-desc">
        Sorry, but the page you are looking for has note been found. Try checking the URL for error, then hit the refresh button on your browser or try found something else in our app.
        <form class="form-inline m-t" role="form">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Search for page">
            </div>
            <button type="submit" class="btn btn-primary">Search</button>
        </form>
    </div>
</div>

inspinia-template/app/views/pages/parse_csv.html.erb
<div class="container">
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Conta</th>
        <th scope="col">Reduzido</th>
        <th scope="col">Descrição</th>
        <th scope="col">Anterior</th>
        <th scope="col">Débitos</th>
        <th scope="col">Créditos</th>
        <th scope="col">Movimento</th>
        <th scope="col">Saldo Atual</th>
      </tr>
    </thead>
    <tbody>
      <% @balancete_imports.each do |row| %>
          <tr>
            <td scope="row"><%= row.cd_financial_account_company %></td>
            <td><%= row.cd_financial_account_company_reduction %></td>
            <td><%= row.financial_account_description %></td>
            <td><%= row.anterior %></td>
            <td><%= row.debt %></td>
            <td><%= row.credit %></td>
            <td><%= row.moviment %></td>
            <td><%= row.current_balance %></td>
          </tr>
        <% end %>
    </tbody>
  </table>
</div>

inspinia-template/app/views/pages/register.html.erb
<div class="middle-box text-center loginscreen   animated fadeInDown">
    <div>
        <h3>Registre-se</h3>
        <p>Crie sua conta e proteja-se</p>
        <form class="m-t" role="form" action="<%= url_for :controller => 'pages', :action => 'login' %>">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Nome" required="">
            </div>
            <div class="form-group">
                <input type="email" class="form-control" placeholder="Email" required="">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" placeholder="Senha" required="">
            </div>
            <button type="submit" class="btn btn-primary block full-width m-b">Registre-se</button>

            <p class="text-muted text-center"><small>Já tem uma conta?</small></p>
            <a class="btn btn-sm btn-white btn-block" href="<%= url_for :controller => 'pages', :action => 'login' %>">Entrar</a>
        </form>
    </div>
</div>

inspinia-template/app/views/pages/search_results.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-9">
        <h2>	Search Page</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="<%= url_for :controller => 'dashboards', :action => 'dashboard_1' %>">Home</a>
            </li>
            <li class="breadcrumb-item">
                Extra Pages
            </li>
            <li class="breadcrumb-item active">
                <strong>	Search Page</strong>
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
<div class="row">
    <div class="col-lg-12">
        <div class="ibox ">
            <div class="ibox-content">
                <h2>
                    2,160 results found for: <span class="text-navy">“Admin Theme”</span>
                </h2>
                <small>Request time  (0.23 seconds)</small>

                <div class="search-form">
                    <form action="<%= url_for :controller => 'dashboards', :action => 'dashboard_1' %>" method="get">
                        <div class="input-group">
                            <input type="text" placeholder="Admin Theme" name="search" class="form-control form-control-lg">
                            <div class="input-group-btn">
                                <button class="btn btn-lg btn-primary" type="submit">
                                    Search
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="search-result">
                    <h3><a href="#">INSPINIA IN+ Admin Theme</a></h3>
                    <a href="#" class="search-link">www.inspinia.com/inspinia</a>
                    <p>
                        Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites
                        still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
                    </p>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="search-result">
                    <h3><a href="#">WrapBootstrap - Bootstrap Themes & Templates</a></h3>
                    <a href="#" class="search-link">https://wrapbootstrap.com/‎</a>
                    <p>
                        WrapBootstrap is a marketplace for premium Bootstrap themes and templates. Impress your clients and visitors while using a single, rock-solid foundation.
                    </p>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="search-result">
                    <h3><a href="#">WrapBootstrap | Facebook</a></h3>
                    <a href="#" class="search-link">https://www.facebook.com/wrapbootstrap‎</a>
                    <p>
                        WrapBootstrap. 13672 likes · 508 talking about this. Marketplace for premium Bootstrap themes and templates. https://wrapbootstrap.com/
                    </p>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="search-result">
                    <h3><a href="#">Wrapbootstrap - Quora</a></h3>
                    <a href="#" class="search-link">www.quora.com/Wrapbootstrap‎‎</a>
                    <p>
                        If you are familiar with using any other HTML/CSS themes or WordPress themes then you shouldn't have any problems. If you have some experience using the ...
                    </p>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="search-result">
                    <h3><a href="#">Newspaper Template - Wrapbootstrap Free download ...</a></h3>
                    <a href="#" class="search-link">https://wrapbootstrap.com/‎‎</a>
                    <p>
                        What's black, white and red all over? The answer is Newspaper. A stylish magazine/news style theme inspired by black and white newsprint. The theme is.
                    </p>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="search-result">
                    <h3><a href="#">Admin Themes Wrapbootstrap</a></h3>
                    <a href="#" class="search-link">https://wrapbootstrap.com/themes/admin‎‎</a>
                    <p>
                        It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                    </p>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="text-center">
                    <div class="btn-group">
                        <button class="btn btn-white" type="button"><i class="fa fa-chevron-left"></i></button>
                        <button class="btn btn-white">1</button>
                        <button class="btn btn-white  active">2</button>
                        <button class="btn btn-white">3</button>
                        <button class="btn btn-white">4</button>
                        <button class="btn btn-white">5</button>
                        <button class="btn btn-white">6</button>
                        <button class="btn btn-white">7</button>
                        <button class="btn btn-white" type="button"><i class="fa fa-chevron-right"></i> </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
